version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      ignore: gh-pages
          steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.
          # command: yarn run build

      - run:
          name: Print the Current Time
          command: date