version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      ignore: gh-pages
      ignore: master
    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date