version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      ignore: gh-pages
    steps:
      - run: echo "Skipping tests on gh-pages branch"

      - run:
          name: Print the Current Time
          command: date